"use client";

import { useState } from "react";
import { saveProfileDraft } from "./profileStore";
import LocalMediaUpload from "./LocalMediaUpload";

type Project = { title: string; client: string; location: string; service: string; completedDate: string; duration: string; budget: string; description: string; challenge: string; solution: string; results: string; beforeImage: string; afterImage: string; testimonial: string; rating: string; visible: boolean };
const emptyProject: Project = { title: "", client: "", location: "", service: "", completedDate: "", duration: "", budget: "", description: "", challenge: "", solution: "", results: "", beforeImage: "", afterImage: "", testimonial: "", rating: "5", visible: true };
const seedProject: Project = { ...emptyProject, title: "Retail Center Pipe Repair", client: "Oak Lawn Shops", location: "Dallas, TX", service: "Commercial pipe repair", duration: "3 days", budget: "$14,600", description: "Repaired a slab leak and replaced damaged supply lines with minimal disruption to the tenants.", rating: "4.6" };

export default function PreviousProjectForm() {
  const [project, setProject] = useState<Project>(seedProject);
  const [notice, setNotice] = useState("");
  const update = (name: keyof Project, value: string | boolean) => setProject((current) => ({ ...current, [name]: value }));
  const save = (draft = false) => setNotice(saveProfileDraft("projects", { items: [project] }, draft));
  return <section className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm sm:p-7">
    <p className="text-xs font-bold uppercase tracking-wider text-[#0b1f3b]">Portfolio manager</p><h2 className="mt-2 text-2xl font-bold text-gray-900">Add a previous project</h2><p className="mt-2 text-sm text-gray-500">Show customers the quality of your completed work, including the problem, solution, and outcome.</p>
    <form onSubmit={(event) => { event.preventDefault(); save(); }} className="mt-7 space-y-5"><div className="grid gap-4 md:grid-cols-2">
      <label className="md:col-span-2"><span className="text-sm font-semibold text-gray-700">Project title</span><input required value={project.title} onChange={(e) => update("title", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="e.g. Whole-home repiping" /></label>
      <label><span className="text-sm font-semibold text-gray-700">Client or property name</span><input value={project.client} onChange={(e) => update("client", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" /></label><label><span className="text-sm font-semibold text-gray-700">Project location</span><input value={project.location} onChange={(e) => update("location", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="City, state" /></label>
      <label><span className="text-sm font-semibold text-gray-700">Service category</span><input required value={project.service} onChange={(e) => update("service", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="Leak repair, water heater, etc." /></label><label><span className="text-sm font-semibold text-gray-700">Completion date</span><input type="date" value={project.completedDate} onChange={(e) => update("completedDate", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" /></label>
      <label><span className="text-sm font-semibold text-gray-700">Project duration</span><input value={project.duration} onChange={(e) => update("duration", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="e.g. 3 days" /></label><label><span className="text-sm font-semibold text-gray-700">Project value</span><input value={project.budget} onChange={(e) => update("budget", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="e.g. $2,500" /></label>
      <label className="md:col-span-2"><span className="text-sm font-semibold text-gray-700">Project overview</span><textarea required rows={3} value={project.description} onChange={(e) => update("description", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="Summarize the work completed." /></label>
      <label><span className="text-sm font-semibold text-gray-700">The challenge</span><textarea rows={4} value={project.challenge} onChange={(e) => update("challenge", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="What problem did the client have?" /></label><label><span className="text-sm font-semibold text-gray-700">Your solution</span><textarea rows={4} value={project.solution} onChange={(e) => update("solution", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="How did your team solve it?" /></label>
      <label className="md:col-span-2"><span className="text-sm font-semibold text-gray-700">Results and customer outcome</span><textarea rows={3} value={project.results} onChange={(e) => update("results", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="Share measurable results or the final outcome." /></label>
      <LocalMediaUpload label="Before photo" value={project.beforeImage} onChange={(value) => update("beforeImage", value)} /><LocalMediaUpload label="After photo" value={project.afterImage} onChange={(value) => update("afterImage", value)} />
      <label><span className="text-sm font-semibold text-gray-700">Customer rating</span><select value={project.rating} onChange={(e) => update("rating", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]"><option value="5">5.0</option><option value="4.5">4.5</option><option value="4">4.0</option></select></label><label className="flex items-end gap-3 pb-3 text-sm font-semibold text-gray-700"><input type="checkbox" checked={project.visible} onChange={(e) => update("visible", e.target.checked)} className="h-4 w-4 accent-[#0b1f3b]" /> Show on public profile</label>
      <label className="md:col-span-2"><span className="text-sm font-semibold text-gray-700">Customer testimonial</span><textarea rows={3} value={project.testimonial} onChange={(e) => update("testimonial", e.target.value)} className="mt-2 w-full rounded-xl border border-gray-200 px-3 py-2.5 text-sm outline-none focus:border-[#FFD60A]" placeholder="Optional customer quote (with permission)." /></label>
    </div>{notice && <p className="rounded-lg bg-emerald-50 px-3 py-2 text-sm font-medium text-emerald-700">{notice}</p>}<div className="flex flex-wrap gap-3 border-t border-gray-100 pt-5"><button type="submit" className="rounded-xl bg-[#0b1f3b] px-4 py-2.5 text-sm font-bold text-white">Save project</button><button type="button" onClick={() => save(true)} className="rounded-xl border border-gray-200 px-4 py-2.5 text-sm font-bold text-gray-700">Save as draft</button><button type="button" onClick={() => { setProject(emptyProject); setNotice(""); }} className="rounded-xl px-4 py-2.5 text-sm font-bold text-gray-500">Clear form</button></div></form>
  </section>;
}
